### ISSUE TITLE
nefunkční Docker verze 18.03.1-ce, build 9ee9f40 na Debian 9

### ISSUE THREAD

**Issue by petrparolek** [vpsfreecz/vpsadminos#15]
`sudo docker run hello-world
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"could not create session key: operation not permitted\"": unknown.
ERRO[0000] error waiting for container: context canceled`

**Comment by landsman** [comment]
https://twitter.com/vojtabiberle/status/998551325758631936

**Comment by aither64** [comment]
Podarilo se nam to castecne rozjet, hledam par testeru. Kdo mate zajem, ozvete se pls na IRC #vpsfree nebo #vpsadminos, napiste ID VPS ze stagingu a nastavime to tak, aby docker v dane VPS fungoval.

Funguje nam `docker run hello-world`, ale chtel bych vedet, jestli funguje i to co pouzivate v praxi -- ja s tim nemam zkusenosti.

Konkretne, na nodu je potreba nastavit:
```
ct set seccomp $ctid /etc/lxc/config/common.seccomp                                                      │
ct set apparmor $ctid osctl-ct-docker-vfs
```

Ve VPS pak funguje docker z repozitaru na docker.com, tzn. verze 18.03. Zkousel jsem to na debian 9 a ubuntu 18.04 (tam je potreba pouzit docker z test repa, stable neni).

**Comment by aither64** [comment]
https://kb.vpsfree.cz/navody/vps/vpsadminos/docker

**Comment by landsman** [comment]
Perfektní, díky za návod!

**Comment by petrparolek** [comment]
přimlouvám se za opravu keyringu https://im.vpsfree.cz/archive/chat.freenode.net/%23vpsadminos/2018/06/22.html#l34 často mi zkalubuje mysql ve spojení s Gitlab CI a buildy padají jako hrušky
