### ISSUE TITLE
Possibility to consider OpenVZ 7

### ISSUE THREAD

**Issue by paulocoghi** [vpsfreecz/vpsadminos#18]
Now that OpenVZ is updated and has a mature new version using a newer kernel, the OpenVZ 7, would you consider to include it in a future version of vpsAdminOS?

**Comment by snajpa** [comment]
(Hell) no. The whole point of vpsAdminOS is to avoid OpenVZ at all.

These days it makes much more sense to deal with upstream kernel problems, when doing containerization, than dealing with a kernel that only a few mad Russians are abe to maintain and even less are truly doing so.

vpsFree started with OpenVZ, but the time to move on was honestly at least two years ago. VZ7 and the whole process around it is a spit in the face of open source, there essentialy is no OpenVZ, only a commercial release.

That would even eventually become the official VZ team attitude - just use unlicensed Virtuozzo 7 and you’ll be better off.

So, no, the time to say goodbye to OpenVZ was at least 2 years ago ;)

**Comment by paulocoghi** [comment]
Thanks for your response and to clarify your reasons! I can perfectly understand your thinking, but I cordially ask your permission to post some information below to help clarify other users that may visit this thread. I am not trying to convince you to think different or change your mind. I just want to clarify things for everyone interested.

**The OpenVZ contributors and community: more than 10k members**
> a kernel that only a few mad Russians are able to maintain and even less are truly doing so

There are more than **[10k members](https://forum.openvz.org/)** on OpenVZ community, between bug reporters, source code/patch contributors and kernel developers. It even happened that over 5,000 members were online and active on the same day.

Of course the majority of them are bug reporters and users looking for help or more information, but this only reinforce that there a lot of people helping in many different ways to make it to be rock solid, as it always has been.

**The source code is completely available**

> there essentialy is no OpenVZ

Of course there is: here is the **[open source iso](https://download.openvz.org/virtuozzo/releases/7.0/x86_64/iso/openvz-iso-7.0.7.iso)** and here is the **[source code](https://src.openvz.org/projects)**.

> VZ7 and the whole process around it is a spit in the face of open source, there essentialy is no OpenVZ, only a commercial release.

VZ7 was the result of making OpenVZ and Virtuozzo the same thing **and** open source, because the control tools was not identical on the previous versions.

Not only [source code of the whole project is available](https://src.openvz.org/projects). We can see a lot of people submitting code to it, including dozens of kernel developers from many countries on the [OpenVZ Kernel source code](https://src.openvz.org/projects/OVZ/repos/vzkernel/commits).

Even more important:

 - the paid features provided on Virtuozzo are external to OpenVZ, like distributed storage
 - more than before, the efforts to merge the differences of OpenVZ kernel and the mainstream Linux kernel are in effect, including the joining efforts of the OpenStack core developers and the results [they are bringing](https://docs.openstack.org/ocata/config-reference/compute/hypervisor-virtuozzo.html)

**Other really interesting things**

 - there are more than **[240k servers reported](https://stats.openvz.org/)** that are running OpenVZ
 - there are servers reporting to be running more than 16k OpenVZ containers, which is really rock solid
 - OpenVZ is fully compatible with [libvirt](https://libvirt.org/drvvirtuozzo.html)
 - with it, it is possible to integrate with [OpenStack](https://docs.virtuozzo.com/virtuozzo_7_users_guide/advanced-tasks/integrating-virtuozzo-7-with-openstack.html) and any other serious cloud orchestration platform
 - the [documentation](https://docs.virtuozzo.com) is constantly updated and it is fully compatible with both open source and commercial version.

I really hope to clarify everyone that may visit this issue. Thanks again, @snajpa, for the space.

**Comment by snajpa** [comment]
Man, I should have made some screenshots from IRC of your very own Vasily Averin recommending a guy just to not bother with OpenVZ and go for the nonfree build.

While I am geatful for what the OpenVZ project has enabled us - we wouldn’t be able to do what we wanted back in 2009 without OpenVZ, I am much less appreciative of where the project ended up now.

Your post is a lot of fluff, but doesn’t reflect reality at all.

Re: the few Russian guys specifically - please can you compile the list of names of non-Virtuozzo employees in the first page of commits, who have contributed to OpenVz specifically?

Because all I can see are ports of patches from Red Hat employees.

You know, the world isn’t blind and if wasn’t for James Bottomley, nobody would have cared about OpenVZ. Cgroups came from Google, after upstream rejected UBC and the last piece of crucial work to get containers in vanilla - user namespace - came from Canonical.

Only after hiring James was there any measurable effort for upstreaming things.

And now, your two most veteran devs are able to do upstream work and are doing just that - but not directly related, they’re the go-to guys for process checkpointing.

So who exactly is working on the open Virtuozzo, who knows anything about the open part of open-source?

**Comment by paulocoghi** [comment]
> please can you compile the list of names of non-Virtuozzo employees in the first page of commits, who have contributed to OpenVz specifically?

I understand your point and, no, I can't, mainly because I am not a Virtuozzo employee and I don't have available time to do this research (that's possible to do, but will take time).

But, at least, we are now talking about a code that anyone can see, change and contribute. Even in the case that (currently) only Virtuozzo employees are contributing to the OpenVZ/Virtuozzo kernel, it's surely not what you said.

It's surely not a commercial product only.

**Comment by paulocoghi** [comment]
> So who exactly is working on the open Virtuozzo, who knows anything about the open part of open-source?

I really hope to contribute, some day. And we will not find people with such advanced knowledge everywhere :)

I just want to take it easy and help to show how many positive things continue to happen with OpenVZ :)

> Your post is a lot of fluff, but doesn’t reflect reality at all.

With exceptions on the the kernel contributions, that at least are visible contributions to an open code, I cordially ask which information I am posting that doesn't reflect the reality.

I posted real information, each one with links, so everyone can confirm what I'm saying.

Just as a user, why I would say different things from reality, if:

 - there are [10,914 openvz registered users right now](https://forum.openvz.org/)
 - the record of simultaneous online users (5370) is public on the same link
 - regardless of who is active in the forum today, there are [84,951 hosts with active openvz containers](https://stats.openvz.org/) running right now
 - And [hundreds of new hosts](https://stats.openvz.org/t.php) are being reported every month.

I have seen a lot of criticism about OpenVZ and I understand some of it. But many of these critics don't see the current progress of the project that is happening right now. :)

Let's take it easy :)

**Comment by paulocoghi** [comment]
> So who exactly is working on the open Virtuozzo, who knows anything about the open part of open-source?

Since English isn't my main language (I am Brazilian), I don't understand your question, as everything related to the system container virtualization on OpenVZ is open to me, and the code is available and ready to receive contributions from anyone. What is the problem here?

I really hope to contribute, some day. And we will not find people with such advanced knowledge everywhere :)

I just want to take it easy and help to show how many positive things continue to happen with OpenVZ :)
