### ISSUE TITLE
Vyladění Dockeru

### ISSUE THREAD

**Issue by petrparolek** [vpsfreecz/vpsadminos#19]
verze OS: Ubuntu 18.04.1
verze Dockeru: 
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:15 2018
  OS/Arch:          linux/amd64
  Experimental:     false

při souběžných více CI jobů sspadne MySQL server:

`PHP E_WARNING: PDO::query(): MySQL server has gone away`

nebo `ERROR: Job failed (system failure): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

bylo by super opravit keyringu https://im.vpsfree.cz/archive/chat.freenode.net/%23vpsadminos/2018/06/22.html#l34 často mi zkalubuje mysql ve spojení s Gitlab CI a buildy padají jako hrušky

**Comment by snajpa** [comment]
A nejaka hlaska z toho MySQL serveru, proc padnul?
