### ISSUE TITLE
CentOS 8: error upgrading filesystem.x86_64

### ISSUE THREAD

**Issue by SemaiCZE** [vpsfreecz/vpsadminos#34]
Hi,
on my CentOS 8 VPS I can't upgrade package `filesystem`. `dnf` command does not specify actual error, but downloading the package and installing via `rpm` command reveals this:

```
error: unpacking of archive failed on file /proc: cpio: chown failed - No such file or directory
error: filesystem-3.8-2.el8.x86_64: install failed
```

Thanks for help,
-Petr

**Comment by SemaiCZE** [comment]
ok, I've found a workaround [link](https://rpm.org/user_doc/faq.html):
```
echo "%_netsharedpath /sys:/proc" >> /etc/rpm/macros.dist
```

**Comment by aither64** [comment]
Thank you for the report and for the solution! I've [put in into the template](https://github.com/vpsfreecz/vpsadminos-image-build-scripts/commit/386493703414f7a397f1b3b5ef4734d7dc7cba2d) which is used to create new VPS with CentOS 8.
