### ISSUE TITLE
After mounting a dataset, CT doesn't start

### ISSUE THREAD

**Issue by PaulosV** [vpsfreecz/vpsadminos#4]
**How to reproduce:**
```
Create a container myctl03
# osctl ct dataset new myctl03 abc
# osctl ct mounts dataset --mountpoint=/mant --opts=ro myctl03 abc
# osctl ct start myctl03
```

Log output:
```
lxc-start myctl03 20180304122003.440 ERROR    lxc_conf - conf.c:mount_entry:1750 - No such file or directory - Failed to mount "/tank/ct/myctl03/abc/private" on "/var/lib/lxc/rootfs/mant"
lxc-start myctl03 20180304122003.440 ERROR    lxc_conf - conf.c:lxc_setup_child:3090 - failed to setup the mount entries for 'myctl03'
lxc-start myctl03 20180304122003.440 ERROR    lxc_start - start.c:do_start:968 - Failed to setup container "myctl03".
lxc-start myctl03 20180304122003.440 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 5)
lxc-start myctl03 20180304122003.440 ERROR    lxc_start - start.c:__lxc_start:1556 - Failed to spawn container "myctl03".
```

**Comment by aither64** [comment]
The mountpoint within the container does not exist. Use `--opts bind,ro,create=dir` to create the directory automatically, see the [docs](https://vpsadminos.org/containers/datasets/#mounting-datasets).

Btw, the dataset has already been mounted to `/abc` when you ran `osctl ct dataset new myctl03 abc`. To change the default mountpoint, you can use `osctl ct dataset new myctl03 abc /mant` and then you don't have to mount it manually at all. The default mount is `rw` though.

**Comment by PaulosV** [comment]
Whoops, then I had no idea this would already be mounted! Thanks for the explanation and doc link, I'll read it better next time.

We mainly filed this bug because of the fail, but we also noticed the weird path `/var/lib/lxc/rootfs/mant` (first line of the log output) where the vpsadminos is apparently trying to mount the thing. Is that normal? When we tried to browse that folder, it was not looking like a rootfs. But this might just be my misunderstanding.

**Comment by aither64** [comment]
Yep, this is how LXC works, afaik :) The container's rootfs is prepared in `/var/lib/lxc/rootfs`, where it's mounted from the zpool, e.g. `/tank/ct/myctl03/private`. All other *mounts are mounted* there as well, this is where it failed. Only the lxc-start process can see the contents of `/var/lib/lxc/rootfs`, because it's in a mount namespace. Then LXC calls `pivot_root`, which makes that directory the root (`/`), and later it starts the container's `/sbin/init` process. At least this is my understanding.
