### ISSUE TITLE
can't deploy apps to dokku

### ISSUE THREAD

**Issue by hovancik** [vpsfreecz/vpsadminos#40]
Hi all, 

I've tried installing dokku on my VPS but had some issues. 

Installing dokku went fine, also adding new app, but when I try to deploy the app via git push, I am getting issues, basically what's described here: https://github.com/dokku/dokku/issues/3454

I've tried the same process on vultr VPS and everything went well, so I am guessing this might be something related to vpsfree as well. 

I was trying production vpsAdminOS and Debian 10, 9 and Ubuntu 20.04 with the same results.

**Comment by snajpa** [comment]
Could you try with vpsAdminOS staging nodes?

It seems to work for me there. The current staging state of vpsAdminOS is scheduled to be deployed next week.

**Comment by hovancik** [comment]
Staging worked fine :)

**Comment by hovancik** [comment]
forgot to ask: where can I see when it will be deployed?
