### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by McSinyx** [vpsfreecz/vpsadminos#62]
I recall raising this elsewhere months ago and receiving a non-definitive answer, so here I am again as a customer asking vpsAdminOS to be released under a free software license.

**Comment by aither64** [comment]
I've added the license info, see bbb42f8640da10fe3a9645b9ae1228d8e2b99f32. Otherwise vpsFree.cz does not have customers, you're possibly a member of our association if that is what you meant to say.

**Comment by McSinyx** [comment]
Thanks, and yes, I forgot about vpsFree's non-profit status, apologies :sweat_smile:
